sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - git-core
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - git
before_install:
  - npm i -g npm@^5.5.1
before_script:
  - git fetch --unshallow origin refs/heads/master:refs/remotes/origin/master
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+(\\-.*)?$/"
